config/routes.rb
Rails.application.routes.draw do
  resources :chars

  root to: 'chars#index'
  devise_for :users
  resources :users

  namespace :api, defaults: {format: :json} do
    resources :task_lists, only: [:index] do
      resources :tasks, only: [:index, :create, :update, :destroy]
    end
  end
end

app/models/char.rb
class Char < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  before_filter :authenticate_user!

  private

  def permission_denied
    render json: {error: 'unauthorized'}, status: :unauthorized
  end
end

app/controllers/api/task_lists_controller.rb
class Api::TaskListsController < Api::BaseController
  before_action :check_owner, only: [:show, :update, :destroy]

  def index
    render json: current_user.task_lists
  end

  def show
    render json: task_list
  end

  def create
    list = current_user.task_lists.create!(safe_params)
    render json: list
  end

  def update
    task_list.update_attributes(safe_params)
    render nothing: true
  end

  def destroy
    task_list.destroy
    render nothing: true
  end

  private
  def check_owner
    permission_denied if current_user != task_list.owner
  end

  def task_list
    @task_list ||= TaskList.find(params[:id])
  end

  def safe_params
    params.require(:list).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chars_controller.rb
class CharsController < ApplicationController
  before_action :set_char, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @chars = Char.all
    respond_with(@chars)
  end

  def show
    @char = Char.find(params[:id])
    respond_with(@char)
  end

  def new
    @char = Char.new
    respond_with(@char)
  end

  def edit
  end

  def create
    @char = Char.new(char_params)
    flash[:notice] = 'Char was successfully created.' if @char.save
    respond_with(@char)
  end

  def update
    flash[:notice] = 'Char was successfully updated.' if @char.update(char_params)
    respond_with(@char)
  end

  def destroy
    @char.destroy
    respond_with(@char)
  end

  private
    def set_char
      @char = Char.find(params[:id])
    end

    def char_params
      params[:char][:user_id] = current_user.id
      params.require(:char).permit(:name, :user_id, :str, :hp, :stats, :updated_at)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chars_helper.rb
module CharsHelper
end

app/helpers/taks_helper.rb
module TaksHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/chars/_form.html.erb
<%= simple_form_for(@char) do |f| %>
<%= f.error_notification %>

<div class="form-inputs">
  <%= f.input :name %>
  <%= f.input :str %>
  <%= f.input :hp %>
  <%= f.input :stats %>
</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>
<br>

app/views/chars/edit.html.erb
<div class="row">
  <div class="well col-md-4 col-md-offset-4">
    <h1>Editing Char</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @char %> |
    <%= link_to 'Back', chars_path %>
  </div>
</div>

app/views/chars/index.html.erb
<div class="row">
  <div class="well col-md-4 col-md-offset-4">
    <h1>Listing Chars</h1>
    <div class="panel panel-default">
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @chars.each do |char| %>
          <tr>
            <td><%= char.name %></td>
            <td>
              <%= link_to 'Show', char, class: "btn btn-default btn-sm" %>
              <%= link_to 'Edit', edit_char_path(char), class: "btn btn-default btn-sm" %>
              <%= link_to 'Destroy', char, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-sm" %>
            </td>
          </tr>
         <% end %>
        </tbody>
      </table>
    </div>
    <%= link_to 'New Char', new_char_path %>
  </div>
  <br>
</div>

app/views/chars/new.html.erb
<h1>New Char</h1>

<%= render 'form' %>

<%= link_to 'Back', chars_path %>

app/views/chars/show.html.erb
<div class="row">
  <div class="well col-md-4 col-md-offset-4">
    <h1><%= @char.name %></h1>
    <div class="panel panel-default">
      <table class="table">
        <thead>
          <tr>
            <th>Str</th>
            <th>Hp</th>
            <th>Stats</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @char.str %></td>
            <td><%= @char.hp %></td>
            <td><%= @char.stats %></td>
            <td>
              <%= link_to 'Edit', edit_char_path(@char) %>
              <%= link_to 'Back', chars_path %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <br>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>